---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:

    - name: Update S3 code bucket
      command: "aws s3 sync /var/www/html s3://{{ s3code }}/ --delete"

    - name: Configure WordPress
      blockinfile:
        path: /var/www/html/wp-config.php
        block: |
          define('WP_HOME', 'http://dev.{{ domain }}.com');
          define('WP_SITEURL', 'http://dev.{{ domain }}.com');